package org.example;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

public class AddnewprojectTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "E:\\ChromeDriver\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void main() {
    driver.get("https://crm.geekbrains.space/project/");
    driver.findElement(By.id("prependedInput")).click();
    driver.findElement(By.id("prependedInput")).sendKeys("Applanatest1");
    driver.findElement(By.id("prependedInput2")).click();
    driver.findElement(By.id("prependedInput2")).sendKeys("Student2020!");
    driver.findElement(By.id("remember_me")).click();
    driver.findElement(By.id("_submit")).click();
    driver.manage().window().setSize(new Dimension(1536, 864));
    driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
    driver.findElement(By.linkText("Создать проект")).click();
    driver.findElement(By.name("crm_project[name]")).click();
    driver.findElement(By.name("crm_project[name]")).sendKeys("Abobkins");
    {
      WebElement element = driver.findElement(By.cssSelector(".responsive-section:nth-child(1) .responsive-cell:nth-child(1) > .control-group:nth-child(5) > .controls"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".responsive-section:nth-child(1) .responsive-cell:nth-child(1) > .control-group:nth-child(5) > .controls")).click();
    driver.findElement(By.name("crm_project[businessUnit]")).click();
    {
      WebElement dropdown = driver.findElement(By.name("crm_project[businessUnit]"));
      dropdown.findElement(By.xpath("//option[. = 'Research & Development']")).click();
    }
    driver.findElement(By.cssSelector(".control-group-choice:nth-child(7) > .controls")).click();
    driver.findElement(By.name("crm_project[businessUnit]")).click();
    driver.findElement(By.name("crm_project[curator]")).click();
    {
      WebElement dropdown = driver.findElement(By.name("crm_project[curator]"));
      dropdown.findElement(By.xpath("//option[. = '0 -*/8']")).click();
    }
    driver.findElement(By.name("crm_project[rp]")).click();
    {
      WebElement dropdown = driver.findElement(By.name("crm_project[rp]"));
      dropdown.findElement(By.xpath("//option[. = '0 -*/8']")).click();
    }
    driver.findElement(By.name("crm_project[administrator]")).click();
    {
      WebElement dropdown = driver.findElement(By.name("crm_project[administrator]"));
      dropdown.findElement(By.xpath("//option[. = '0 -*/8']")).click();
    }
    driver.findElement(By.name("crm_project[manager]")).click();
    {
      WebElement dropdown = driver.findElement(By.name("crm_project[manager]"));
      dropdown.findElement(By.xpath("//option[. = 'Антонов Дмитрий']")).click();
    }
    driver.findElement(By.cssSelector(".btn-group:nth-child(4) > .btn")).click();
    System.out.println("Test ended sucessfully!");
  }

}
