package org.example;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.AfterEach;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.logging.LogEntries;
import org.openqa.selenium.logging.LogEntry;
import org.openqa.selenium.logging.LogType;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.assertTrue;

public class AddnewprojectTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "E:\\ChromeDriver\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    LogEntries browserLogs = driver.manage().logs().get(LogType.BROWSER);
    List<LogEntry> allLogRows = browserLogs.getAll();
    if (allLogRows.size() > 0 ) {
      for(LogEntry info : allLogRows){

        System.out.println(info);
      }
    }
    driver.quit();
  }
  @Test
  public void main() {
    driver.get("https://crm.geekbrains.space/project/");
    AutorizationPage autorizationPage = new AutorizationPage(driver);
    autorizationPage.clickLoginformUsername().setLoginformUsername("Applanatest1");
    autorizationPage.clickLoginformPassword().setLoginformPassword("Student2020!");
    autorizationPage.clickRememberMe();
    autorizationPage.clickLogin();
    driver.manage().window().setSize(new Dimension(1536, 864));
    driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
    AddNewProjectPage addNewProjectPage = new AddNewProjectPage(driver);
    addNewProjectPage.clickCreateProject();
    addNewProjectPage.clickProjectName().setProjectName("Abobkins");
    {
      WebElement element = driver.findElement(By.cssSelector(".responsive-section:nth-child(1) .responsive-cell:nth-child(1) > .control-group:nth-child(5) > .controls"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".responsive-section:nth-child(1) .responsive-cell:nth-child(1) > .control-group:nth-child(5) > .controls")).click();
    addNewProjectPage.clickCrmProjectBusiness();
    addNewProjectPage.clickCrmProjectBusinessWebElement();
    driver.findElement(By.cssSelector(".control-group-choice:nth-child(7) > .controls")).click();
    addNewProjectPage.clickCrmProjectBusiness();
    addNewProjectPage.clickCrmProjectCurator();
    addNewProjectPage.clickCrmProjectCuratorWebElement();
    addNewProjectPage.clickCrmProjectRp();
    addNewProjectPage.clickCrmProjectRpWebElement();
    addNewProjectPage.clickCrmProjectAdministator();
    addNewProjectPage.clickCrmProjectAdministatorWebElement();
    addNewProjectPage.clickCrmProjectManager();
    addNewProjectPage.clickCrmProjectManagerWebElement();
    assertTrue(driver.findElement(By.cssSelector(".btn-group:nth-child(4) > .btn")).isEnabled());
    driver.findElement(By.cssSelector(".btn-group:nth-child(4) > .btn")).click();
    System.out.println("Test ended sucessfully!");
  }

}
